- Makefile
- agent/agent.go
- agent/request.go
- go.mod
- sdk/context.go
- sdk/context_test.go
- sdk/sdk_suite_test.go
- tools/testlib/rand.go
Ignore SDK calls when:
- the agent is disabled.
- the sdk context is nil (eg. the middleware wasn't used).
> sdk: ignore SDK calls when disabled or context is nil

- Makefile
- agent/agent.go
- agent/backend/client.go
- agent/config/config.go
- agent/config/config_test.go
No longer use ginkgo and rather replace it by the simple standard Go's test
APIs, along with testify for assertions. It makes much easier to write
table-driven tests and control test parallelism. For example, configuration
tests cannot run in parallel and are perfectly suitable for table-driven tests.
> config: test using the standard go test api

- sdk/middleware/gin/gin.go
Add the SDK's HTTP context pointer into the request context so that it can be
retrieved by subfunctions being passed the request context. They can this way
retrieve the SDK's HTTP context pointer out of it anywhere down the call stack.
The previous implementation of GetHTTPRequest() was renamed
GetHTTPRequestFromGin() by convenience as it should be used less often than the
new GetHTTPRequest() which expects a Go context now.
> sdk: store the sdk context in request contexts

- agent/agent.go
- agent/backend/client.go
- agent/backend/client_test.go
- agent/client.go
- agent/config/config.go
The organization token is similar to existing app tokens, but they start with
`org_` and must go with an app name. The backend registers this logging app
under the given name and returns a session token for subsequent calls.
Regular app tokens are still supported.
> agent: organization token

- Makefile
- agent/backend/client.go
- agent/backend/client_test.go
Take into account `{HTTPS,HTTP,NO}_PROXY` environment variables (and their lowercase alternatives) when `SQREEN_PROXY` is not set. This way, the system's configuration is taken into account when defined.
Users not yet using proxies and not willing to impact their normal http requests can just use `SQREEN_PROXY` to explicitly tell the agent to use a given proxy.
Closes SQR-5316
> agent/backend: use *_PROXY environment variables proxy settings

- agent/config/config.go
- agent/config/config_test.go
Create a local viper config to avoid conflicts with global ones.
Closes SQR-5211
> agent/config: avoid conflicts with global viper configs

- sdk/middleware/sqgin/gin.go
To avoid name collisions with gin's package, rename it to `sqgin`. Now users no longer need to rename their middleware import to `sqreen_middleware` as documented. Another benefit is with tools such as `goimport` which will be able to automatically find the package.
Elegant naming idea taken New Relic ;)
Related to SQR-5344.
> SDK middleware naming

- agent/request.go
- sdk/context.go
- sdk/context_test.go
- sdk/event.go
- sdk/middleware/sqgin/gin.go
- sdk/middleware/sqgin/gin_test.go
- sdk/record.go
- sdk/sdk_test.go
Closes SQR-5213, SQR-5344, SQR-5345 and SQR-5346.
> sdk: cleaner api

- sdk/middleware/sqhttp/http.go
- sdk/middleware/sqhttp/http_test.go
Middleware function for `net/http` storing the SDK handle into the request
context, so that it can be later accessed by sub-handlers.
Note that this is the most generic middleware implementation in Go, that can be
used with other frameworks such as Gorilla or Mux. So thanks to this middleware
function, we indirectly support more frameworks when their API allows it.
Closes SQR-5084
> sdk/middleware/sqhttp: middleware function for net/http

- agent/config/config.go
- agent/config/config_test.go
- tools/testlib/rand.go
To allow our users to store their configuration files into different locations, according to their use cases, the configuration file location can now be enforced with environment variable `SQREEN_CONFIG_FILE`. Otherwise, the configuration file is searched into the current working directory first, and then the executable directory.
Closes SQR-5390 and SQR-5389
> agent/config: look for configuration file locations

- CHANGELOG.md
- agent/version.go
- sdk/sdk_test.go
- sdk/user.go
Make the SDK method `Identify()` public so that it is now possible to explicitly
associate a user to the current request. As soon as we add the support for the
security reponses, it will allow to block users.
> sdk: explicit user identification method

- agent/agent.go
- agent/internal/agent.go
- agent/internal/app/runtime.go
- agent/internal/backend/client.go
- agent/internal/backend/client_test.go
- agent/internal/client.go
- agent/internal/config/config.go
- agent/internal/config/config_test.go
- agent/internal/metrics.go
- agent/internal/plog/plog.go
- agent/internal/plog/plog_test.go
- agent/internal/request.go
Refactor the agent so that it no longer relies on Go globals whose life-cycles are managed by the Go runtime, while we would like to be able te manage them ourselves to restart and stop the agent.
In order to be able to properly quit, restart or stop the agent, replace every global variable by structure members, whose life-cycle depends on the agent's: when the agent is initialized/deinitialization, it is now responsible of each data initialization/deinitialization, and the same applies recursively to sub-objects.
Another benefit will be better testing, as every dependency is now exposed in the interfaces, so they will be mockable as we did for the SDK to reach 100% coverage.
> agent: replace globals with struct members

- agent/types/types.go
- sdk/agent.go
- sdk/middleware/sqecho/echo.go
- sdk/middleware/sqecho/echo_test.go
- sdk/middleware/sqgin/gin.go
- sdk/middleware/sqgin/gin_test.go
- sdk/middleware/sqhttp/http.go
- sdk/middleware/sqhttp/http_test.go
- sdk/record.go
- sdk/request.go
- sdk/sdk_test.go
- tools/testlib/agent.go
Implement the ability to block a request at the request handler-level using a new abstract agent entrypoint called `SecurityAction()` which can return a blocking action to be applied to the current request before aborting it.
It will allow to implement blocking IP addresses when a new request is received and of course before user handlers are called.
> sdk: security action interface for requests

- agent/internal/backend/api/api.go
Remove `omitempty` json tags as the backend expects them, even if the value is
the zero value.
> agent/backend/api: fix missing expected backend message keys

- agent/internal/config/config.go
- agent/internal/config/config_test.go
- agent/internal/request.go
`SQREEN_STRIP_HTTP_REFERER`), whose boolean value is true when set to a non-empty
value, false otherwise.
Note that it is intentionally named after the `referer` HTTP header, including the missing `r` letter.
> Configurable stripping of the referer http header

- agent/internal/agent.go
- agent/internal/request.go
Add simple logic to add and send the request record only when necessary, ie.
only when there are some events other than a single identify. To do so, add a
simple boolean value in the record to keep track of when the record should be
sent of not.
Closes SQR-6245.
> agent: fix empty request records only having metrics or identify events

- agent/internal/agent.go
- agent/internal/plog/plog.go
Early logs happening before the agent actual starting do not show up because the
loggers are not yet enabled. Move the enabling in the agent initialization so
that we can see early logs.
> agent/plog: fix early logs not showing up

- agent/internal/config/config.go
- agent/internal/request.go
- agent/internal/request_test.go
The length of an IP address cannot be read using `len(ip)` because some `net`
package functions return a 16-byte slice even for IPv4 addresses. The only way
to safely check if an IP address is a v4 or v6 is to use `ip.To4()` which checks
the internals and returns nil if it's not.
Closes SQR-6259
> agent: fix wrong IP address length checks

- agent/internal/config/config.go
The User-Agent is already included in the request record, so remove it from the
list of tracked headers to avoid sending it twice in the same request record.
Closes SQR-6261.
> agent: remove the User-Agent stored twice in the request record

- agent/internal/config/config.go
- agent/internal/request.go
- agent/internal/request_test.go
- go.mod
The HA Proxy header `X-Unique-Id` can be added using a user-configured format
that may include the IP address. To be able to properly parse it, the agent
needs to be given the format string that is used to generate the header value so
that it can parse it back and find the IP address in it.
The configuration should be:
```
ip_header: X-Unique-Id
ip_header_format: <your format>
```
For now, `ip_header_format` value is only used as a boolean value to activate
this behaviour, but with a hard-coded format: the client IP address first, in
hexadecimal number, followed by a semicolon (port number separator).
Closes SQR-6191
> agent: add custom IP header parser to support HA Proxy Unique Request ID

- agent/internal/actor/treev4.go
- agent/internal/actor/treev4_test.go
Use the Go package `kentik/patricia` as a radix-tree data-structure and define a custom API on top of it providing insertion and lookup of security actions. The underlying radix tree stores uint8 tags, used as indices in an array of actions. Only one action is stored by CIDR and the last one that was added is kept.
Note that methods are not thread-safe and users of this package should only handle this when required.
> Security automation: IPv4 radix tree

- agent/internal/agent.go
- agent/internal/command.go
- agent/internal/command_test.go
- agent/internal/config/config.go
- agent/internal/request.go
- agent/internal/request_test.go
- agent/types/types.go
- tools/testlib/agent.go
> Security automation: update the agent logic

- agent/internal/command.go
- agent/internal/command_test.go
Avoid repeating commands received in a single heartbeat by performing them once
and answering to repeated same commands with the first result that was obtained.
It allows to be more robust to backend errors such as asking to reload actions
multiple time in the same heartbeat response.
>  agent/command: avoid repeating commands

- agent/internal/backend/api/jsonpb.go
- agent/internal/backend/client_test.go
The fuzzy tests highlighted the case where the event type had a double-quote `"` which
was concatenated to the JSON string without being escaped, leading to a broken JSON
string such as:
```
{"event_type:"event"type", ...}
```
This is fixed by escaping the string using the JSON marshaler and appending the returned
value to the JSON.
> agent/backend/client/api: escape the batch event type name string

- agent/internal/agent.go
- agent/internal/request.go
- agent/types/types.go
- go.mod
- go.sum
- sdk/agent.go
- sdk/middleware/sqecho/echo.go
- sdk/middleware/sqecho/echo_test.go
- sdk/middleware/sqgin/gin.go
- sdk/middleware/sqgin/gin_test.go
- sdk/middleware/sqhttp/http.go
- sdk/middleware/sqhttp/http_test.go
- sdk/request.go
- sdk/sdk_test.go
- sdk/user.go
- tools/testlib/agent.go
- Adapt the existing security response API so that it can match identified users
per request. The `SecurityResponse()` method was therefore moved from the
agent interface to the request record interface so that it is now a
per-request method with full access and visibility to the recorded user.
- The new per-user method `MatchSecurityResponse()` allows to check from request
handlers and sub-functions if a user has a security response. The main reason
why we are not using `panic()` to abort the current request from `Identify()`
is that a `panic()` cannot be catched from outside of the calling goroutine,
leading to a crash.
Method `MatchSecurityResponse()` returns an error to allow bubbling up the
error using the usual Go error handling (ie. returning it to the caller). So
that any caller …
> Security automation: SDK to apply security responses by user-identifiers (1/2)

- agent/sqlib/safe/call.go
- agent/sqlib/safe/call_test.go
- agent/sqlib/safe/doc.go
- agent/sqlib/safe/go.go
- agent/sqlib/safe/go_test.go
This package provides functions making sure panics are safely caught and do not
break the running program. Since panics can stop the program execution if they
are not recovered, we need ways to safely recover and handle them.
Therefore, this package provides simple function call wrappers to call a
function that may panic and its goroutine equivalent. That way, any function can
be safely called and any panic will be returned as a regular function error.
> Error management: add panic-safe function and goroutine wrappers (2/5)

- agent/agent.go
- agent/internal/agent.go
- agent/internal/metrics.go
- agent/sqlib/sqsafe/call.go
- agent/sqlib/sqsafe/call_test.go
- agent/sqlib/sqsafe/doc.go
- agent/sqlib/sqsafe/go.go
- agent/sqlib/sqsafe/go_test.go
- agent/sqlib/sqtime/backoff.go
- Backoff restart the agent when it returns an error or a panic, which means it couldn't be handled.
- Replace bare calls to the `go` builtin by the `safe.Go()` wrapper in order to catch goroutine panics (to avoid program crashes).
> Error Management: backoff the agent restart on error or panic (3/5)

- agent/internal/actor/action.go
- agent/internal/actor/action_test.go
- agent/internal/actor/actor.go
- agent/internal/actor/http.go
- agent/internal/backend/api/api.go
- agent/internal/backend/api/jsonpb.go
- agent/internal/request.go
- agent/internal/rule/callback.go
- agent/internal/rule/callback/write-http-redirection.go
- agent/internal/rule/callback/write-http-redirection_test.go
Implement the redirection security response of playbooks:
This leads to the full support of playbooks.
> Redirection security response for playbooks

- agent/internal/backend/api/jsonpb.go
- agent/internal/rule/callback.go
- agent/internal/rule/callback/add-security-headers.go
- agent/internal/rule/callback/add-security-headers_test.go
- sdk/middleware/sqecho/echo.go
- sdk/middleware/sqecho/echo_test.go
- sdk/middleware/sqgin/gin.go
- sdk/middleware/sqgrpc/grpc.go
- sdk/middleware/sqhttp/http.go
Add the support for the security headers rule by having a new hook point allowing to insert headers. To do so, a common HTTP middlewares is created and used to create other middlewares for other Go web frameworks.
> Security headers

- agent/internal/rule/callback.go
- agent/internal/rule/callback/add-security-headers.go
- agent/internal/rule/callback/add-security-headers_test.go
- agent/internal/rule/callback/write-custom-error-page.go
- agent/internal/rule/callback/write-custom-error-page_test.go
- agent/internal/rule/callback/write-http-redirection.go
- agent/internal/rule/callback/write-http-redirection_test.go
- agent/internal/rule/callback_test.go
- agent/internal/rule/rule.go
- agent/sqlib/sqhook/hook.go
The CSP security headers rule attaches a callback to the same hook point as the security headers rule. Since the agent has the full list of callbacks and hook points, it can therefore chain them together when instantiating the callback. So now, a prolog callback has a pointer to the next prolog callback, and same for epilog callbacks. This callback-level chaining allows to:
- keep `sqhook` library as it is, without introducing an array of callbacks that would have been heavier to atomically modify.
- keep the fast dispatch we have for native callbacks by using type-assertion instead of `reflect.Call`.
> CSP security headers

- agent/internal/agent.go
- agent/internal/backend/api/api.go
- agent/internal/metrics.go
- agent/internal/metrics/metrics.go
- agent/internal/metrics/metrics_test.go
- agent/internal/request.go
- agent/internal/rule/callback.go
- agent/internal/rule/callback/add-security-headers.go
- agent/internal/rule/callback/add-security-headers_test.go
- agent/internal/rule/callback/callback_test.go
- agent/internal/rule/callback/monitor-http-status-code.go
- agent/internal/rule/callback/monitor-http-status-code_test.go
- agent/internal/rule/callback/types.go
- agent/internal/rule/callback/write-custom-error-page.go
- agent/internal/rule/callback/write-custom-error-page_test.go
- agent/internal/rule/callback/write-http-redirection.go
- agent/internal/rule/callback/write-http-redirection_test.go
- agent/internal/rule/callback_test.go
- agent/internal/rule/rule.go
- agent/internal/rule/rule_test.go
- sdk/middleware/sqecho/echo.go
- sdk/middleware/sqgin/gin.go
- sdk/middleware/sqhttp/http.go
The monitoring of http status codes is attached to the http response writer. Unfortunately, most frameworks don't use the standard http response writer that we instrument and I had to implement a hack for Gin and Echo to monitor the status code.
As of gRPC, it doesn't seem to be possible to get the http status code it will return from the interceptors so we will wait for the future compiler-inserted hook points in order to attach to internal gRPC http transport methods in order to get the status code.
> HTTP Status Code Metrics

- agent/internal/backend/api/api.go
- agent/internal/batch.go
- agent/internal/rule/callback/waf.go
- agent/sqlib/sqerrors/errors.go
- agent/sqlib/sqerrors/errors_test.go
Further manage the WAF errors by:
- ignoring timeout error instead of reporting them as errors.
- add extra information to the reported error.
> agent/waf: advanced error management

- agent/sqlib/sqsanitize/sanitize.go
- agent/sqlib/sqsanitize/sanitize_test.go
Add a new library to scrub values given two regular expressions:
- The `value` regular expression is used against every string value. The matching part gets redacted.
- The `key` regular expression is used against every map key of type string and every structure field name. When matching, every string in their associated value is redacted, regardless of the `value` regular expression.
The `Scrub()` method scrubs the value in-place. It uses the `reflect` package and it therefore ignores unexported structure field since they cannot be modified.
This package will be used to perform PII scrubbing of Go values before sending them.
> Add a string scrubbing package

- agent/internal/agent.go
- agent/internal/config/config.go
- agent/internal/config/config_test.go
- agent/internal/record/record.go
- agent/sqlib/sqsanitize/sanitize.go
- agent/sqlib/sqsanitize/sanitize_test.go
- tools/testlib/testmock/request-record.go
Every batched event is now scrubbed after being converted into a backend API value and before adding it into the backend API batch.
The scrubber settings are statically defined for now and matches our doc (https://docs.sqreen.com/guides/how-sqreen-works/#pii-scrubbing).
> PII scrubbing of every batched events

- sdk/middleware/sqhttp/http.go
Add the agent import into the SDK so that it is no longer required to import the agent into the main package. The SDK middleware functions were already mandatory to integrate the agent into the app framework.
> Simpler installation by importing the Agent from the SDK

- agent/internal/agent.go
- agent/internal/app/runtime.go
- agent/internal/backend/api/api.go
- agent/internal/backend/client.go
- agent/internal/client.go
- agent/internal/command.go
- agent/internal/command_test.go
- agent/internal/config/config.go
Go programs compiled using the new Go modules support now have their list of dependencies and versions available at run time. Send them to Sqreen so that we can perform our dependency analysis.
> Send the list of dependencies

- sdk/middleware/sqecho/echo.go
- sdk/middleware/sqecho/echo_test.go
- sdk/middleware/sqgin/gin.go
- sdk/middleware/sqgin/gin_test.go
- sdk/middleware/sqhttp/http.go
- sdk/middleware/sqhttp/http_test.go
Fix the monitoring of status codes set by request handlers:
- on gin and echo: simply use the status field of the response field of the
request context value.
- on net/http: pass the response writer that is already used by sqreen handlers.
> sdk/middleware/{sqgin,sqecho,sqhttp}: fix monitoring of request handler status codes

- internal/backend/client_test.go
- internal/client.go
- internal/config/config.go
New org tokens are now linked to an environment and their naming convention has changed from `org_*` to `env_org_*`. This leads to a wrong error message when the `app_name` isn't set. This patch loosely checks the token and checks it contains `org_` as its purpose is only about providing a better error message when the configuration is wrong.
> Update the token validation with the new format

- internal/agent.go
- internal/backend/api/json_test.go
- internal/backend/client.go
- internal/backend/client_test.go
- internal/client.go
- internal/config/config.go
- internal/config/config_test.go
- internal/sqlib/sqsanitize/sanitize.go
- internal/sqlib/sqsanitize/sanitize_test.go
The PII sanitizer - aka PII scrubber - is now configurable using
`strip_sensitive_key_regexp` and `stip_sensitive_value_regexp` configuration
entries.
Because those regular expressions are critical, configuration validation was
added to make sure the regular expressions are valid. The agent doesn't start if
invalid, displaying an error message in the logs.
Some rework around the configuration validation was therefore also performed,
such as the app credential validation.
> Configurable PII sanitizer

- internal/backend/api/json.go
- internal/backend/api/json_test.go
Avoid the string concatenation and rather use `json.Marshal` to safely marshal header keys and values.
> Fix HTTP header marshaling

- internal/sqlib/sqhook/test/testdata/hello-gls/main.go
- internal/sqlib/sqhook/test/tool_test.go
- sdk/sqreen-instrumentation-tool/ast.go
- sdk/sqreen-instrumentation-tool/compile.go
- sdk/sqreen-instrumentation-tool/instrumentation.go
- sdk/sqreen-instrumentation-tool/main.go
- sdk/sqreen-instrumentation-tool/visitor.go
Goroutines already have a descriptor in the runtime with some context in it but
none is available for "gls" (goroutine local storage). This patch adds a `sqgls`
field to the goroutine descriptor type `g`, along with a getter and setter
functions. This way, we get the best possible way of implementing a GLS with
O(1) and a non-concurrent access to the GLS.
The instrumentation is straightforward while the instrumentation tool had to be
refactored in order to be able to handle distinct types of instrumentation
according the package being compiled.
> sdk/sqreen-instrumentation-tool: runtime instrumentation adding gls

- internal/backend/api/api.go
- internal/protection/http/http.go
- internal/rule/callback/javascript.go
- internal/sqlib/sqgls/gls.go
- internal/sqlib/sqgls/gls_sqreen.go
- internal/sqlib/sqhook/test/testdata/hello-gls/main.go
- sdk/sqreen-instrumentation-tool/instrumentation.go
Store the HTTP protection context in the GLS when it is created, so that
functions not having direct access to it, nor to the request context, can now
access it through the GLS. Therefore, the security rules no longer need the
`context` field that was specifying how to access it through function arguments.
Therefore, GLS is now mandatory, as most of the RASP protections need it. For
example, functions like `os.Open()` or `exec.(*Command).Run()` can now be
protected thanks to this change.
> agent: goroutine local storage integration

- internal/binding-accessor/binding-accessor.go
- internal/binding-accessor/binding-accessor_test.go
- internal/binding-accessor/exec.go
- internal/rule/callback/bindingaccessor_test.go
- internal/rule/callback/bindingaccessors.go
- sdk/sqreen-instrumentation-tool/instrumentation.go
This patch updates the instrument tool so that the `os` package is instrumented and we can monitor and protect calls to `os.StartProcess` against shell injections. Go doesn't have any shell expansion and so on in the std library, but `os.StartProcess` can be used to execute a shell or shell script and we can therefore check for injections in the list of arguments.
The rest of the patch adds support to binding accessors for function calls with multiple arguments, along with a new helper function `#.Lib.Array.Prepend` that we didn't have to use in the security rule in the end.
So the good news is that the current JS callback was already suitable for this new security rule.
> RASP: Shell-Injection Protection

- internal/actor/action.go
- internal/actor/actor.go
- internal/actor/iplist.go
- internal/actor/iplist_test.go
- internal/adapter.go
- internal/agent.go
- internal/metrics.go
- internal/protection/context/context.go
- internal/protection/http/bindingaccessor.go
- internal/protection/http/http.go
- internal/protection/http/types/types.go
- internal/record/record.go
- internal/rule/callback/add-security-headers_test.go
- internal/rule/callback/callback_test.go
- internal/rule/callback/factory.go
- internal/rule/callback/ip-denylist.go
- internal/rule/callback/ip-denylist_test.go
- internal/rule/callback/monitor-http-status-code_test.go
- internal/rule/callback/testdata/testrules/main.go
- internal/rule/callback/waf_test.go
- internal/rule/callback/write-custom-error-page.go
- internal/rule/callback/write-custom-error-page_test.go
- internal/rule/callback/write-http-redirection_test.go
- sdk/middleware/_testlib/mockups/agent.go
- sdk/middleware/sqecho/echo_test.go
- sdk/middleware/sqgin/gin_test.go
- sdk/middleware/sqhttp/http_test.go
- sdk/types/types.go
- sdk/types/types_test.go
Add a native callback to check if an IP address is in the IP denylist.
Integrate it into a new HTTP protection method `isIPBlocked` which
returns a non-nil error when the IP is blocked and the request was
handled. 
This small patch went big in the end to remove every usage of whitelist
and blacklist in the code (when possible).
> Add IP denylist support

- internal/rule/callback/javascript.go
Allow custom error handling and integration by returning the SDK error wrapper.
`errors.As()` can be used to check if the returned error comes from Sqreen protections.
> Return the sdk error wrapper when blocking

- internal/backend/api/api.go
- internal/backend/api/json.go
- internal/binding-accessor/binding-accessor.go
- internal/binding-accessor/exec.go
- internal/rule/callback/bindingaccessor_test.go
- internal/rule/callback/bindingaccessors.go
- internal/rule/callback/javascript.go
- sdk/sqreen-instrumentation-tool/tool_test.go
Remove the hard-coded map of SQL dialects per package paths and make it
rule-defined. To do so, the `SQL.Dialect()` function was modified so that the
map can be provided as a second argument. The map is now defined in the SQLi
rule and made accessible to binding accessors through the new `rule`
capability. This new capability adds a new `Rule` field to the binding accessor
context, giving access to the rule data, where the map is defined in the SQLi
rule. The new binding accessor is therefore:
`#.SQL.Dialect(#.Func.Args[1], #.Rule.Data.Values['dialects'])`.
> RASP: enhanced sql package support

- internal/binding-accessor/binding-accessor.go
- internal/rule/callback/bindingaccessor_test.go
- internal/rule/callback/bindingaccessors.go
- internal/rule/callback/javascript.go
- internal/rule/callback/waf.go
Assuming the binding accessor context is created per call-site, request, and
security rule, we can add some simple caching of binding accessor results and
reuse them when the binding accessor expression is the same. This cache isn't
shared at all and doesn't need any invalidation nor thread-safety mechanism.
It is useful to use when a rule uses several times the same binding accessor
expressions, such as the In-App WAF.
Integrate it to:
- The JS callback through a new capability `cache` to make it optional, and
disabled by default.
- The In-App WAF which likely uses lots of binding accessors.
> Callback: binding accessor result caching

- internal/protection/http/http.go
- internal/protection/http/request.go
Mainly for debugging purposes, split the existing file in two so that we can
have one that is not instrumented thanks to the `sqreen:ignore` directive.
> protection/http: finer-grained instrumentation

- sdk/sqreen-instrumentation-tool/instrumentation.go
Instrument mongodb.org/mongo-driver/mongoI/mongo.go in order to attach noSQL-injection protection to the driver.
> sdk/sqreen-instrumentation-tool: add limited instrumentation of go.mongodb.org/mongo-driver/mongo

- internal/agent.go
- internal/backend/api/signal/signal.go
- internal/backend/client.go
I think the staleness timer could be triggered during the initialization and lead to the empty batch being sent.
This patch changes the initial duration to 24 hours to make sure it cannot trigger during the loop initialization.
> Fix a possible empty batch being sent

- internal/backend/api/api.go
- internal/backend/api/json_test.go
- internal/sqlib/sqsanitize/sanitize.go
- internal/sqlib/sqsanitize/sanitize_test.go
Change the scrubbing function of the WAF metadata to sanitize substrings and not
only the full string value.
> scubbing: fix the waf metadata scrubbing

- internal/backend/api/signal/signal.go
- internal/rule/callback/shellshock.go
- internal/rule/callback/shellshock_unit_test.go
- internal/rule/factory.go
The shellshock protection is attached to `os.StartProcess()` and checks the environment variables against a list of regular expressions. When matching, the call is aborted and the request blocked.
> RASP: add shellshock protection

- internal/backend/api/signal/signal.go
Avoid dropping an http trace when a port number cannot be parsed.
> agent/backend/signal: do not drop a trace on empty port numbers

- internal/adapter.go
- internal/protection/http/bindingaccessor.go
- internal/protection/http/bindingaccessors_test.go
- internal/protection/http/http_test.go
- internal/protection/http/request.go
- internal/protection/http/types/types.go
- internal/rule/callback/ip-denylist_test.go
- sdk/middleware/sqecho/echo.go
- sdk/middleware/sqgin/gin.go
- sdk/middleware/sqhttp/http.go
- sdk/middleware/sqhttp/http_test.go
- sdk/sqreen-instrumentation-tool/instrumentation.go
Remove the current call to `ParseForm()` in the middlewares in favor of a direct
access to the cached value in the `Request` structure. This value is not nil
when the request handler has called `ParseForm()` itself. Meaning that the
In-WAF and RASP protections will now only consider the POST form values of the
request when actually parsed by the request handler.
Note that the In-App WAF is now dynamically attached to `ParseForm()` which
returns a non-nil error of type `*SqreenError` when blocked by the In-App WAF
(cf. https://docs.sqreen.com/go/integration for more details).
This fixes the usage of the Go agent in a reverse proxy server where the agent
was consuming the body because of the call to `ParseForm()`, making later reads
to `Request.Body` return EOF. A server can now correctly …
> agent/protection/http: lazy access to post form values

- internal/agent.go
- internal/backend/api/api.go
- internal/rule/callback.go
- internal/rule/callback/callback_test.go
- internal/rule/callback/javascript.go
- internal/rule/callback/shellshock.go
- internal/rule/callback/types.go
- internal/rule/callback/waf.go
- internal/rule/rule.go
Implement the activity monitoring displayed on the dashboard, showing the number
of times a security rule has been called. This feature is enabled when the rule's
`call_count_interval` is not 0.
For now only deployed only on the In-App WAF and RASP callbacks.
> Call Count Monitoring of RASP and In-App WAF callbacks

- sdk/sqreen-instrumentation-tool/instrumentation.go
Enable partial instrumentation of Echo in order to run the In-App WAF when the body is parsed into a Go object. This is achieved thanks to a security rule dynamically attaching the In-App WAF to Echo's `Bind()` method.
> Enable partial instrumentation of Echo

- internal/rule/callback/shellshock.go
Fix the environment variable lookup when other variable assignments are in the value.
> agent/rule/shellshock: fix splitting environment variables

- internal/backend/api/api.go
- internal/backend/api/api_test.go
- internal/sqlib/sqsanitize/sanitize.go
- internal/sqlib/sqsanitize/sanitize_test.go
Replace the use of `strings.ReplaceAll()` with a case-insensitive regular
expression of the request parameter so that it also matches attack information
that got transformed by the In-App WAF (eg. lower-cased).
> PII: fix In-App WAF attack sanitization

- sdk/middleware/sqecho/echo_test.go
- sdk/middleware/sqgin/gin.go
- sdk/middleware/sqgin/gin_test.go
- sdk/middleware/sqhttp/http_test.go
This fixes a bug where gin's `c.Request`'s context gets overwritten by the `sqgin` middleware
If you set some values in the context of `c.Request`, you won't be able to retrieve them after  `sqgin`'s 'middlewareHandler' has done its work
> sdk/middleware/sqgin: fix request ctx

- sdk/middleware/_testlib/mockups/http.go
- sdk/middleware/sqecho/echo.go
- sdk/middleware/sqecho/echo_test.go
- sdk/middleware/sqecho/v4/echo.go
- sdk/middleware/sqecho/v4/echo_test.go
Monitor the return error of Echo request handlers to see if they are Echo's
HTTPErrors, so that we can properly capture the HTTP status code that will be
later used by Echo. The HTTP response is indded out of the middleware scope in
that case.
> sdk/middleware/echo: fix status code monitoring of handler errors

- internal/actor/actor_test.go
- internal/agent.go
- internal/backend/client_test.go
- internal/command_test.go
- internal/config/config_test.go
- internal/plog/plog.go
- internal/plog/plog_test.go
- internal/rule/callback.go
- internal/rule/callback/_testlib/mockups/mockups.go
- internal/rule/callback/context.go
- internal/rule/callback/ip-denylist.go
- internal/rule/callback/ip-denylist_test.go
- internal/rule/callback/javascript.go
- internal/rule/callback/monitor-http-status-code.go
- internal/rule/callback/monitor-http-status-code_test.go
- internal/rule/callback/security-responses.go
- internal/rule/callback/shellshock.go
- internal/rule/callback/waf.go
- internal/rule/callback/write-blocking-html-page.go
- internal/rule/callback/write-http-redirection.go
- internal/rule/callback_test.go
- internal/rule/rule.go
- internal/rule/rule_test.go
- internal/sqlib/sqassert/sqsync/map.go
- internal/sqlib/sqerrors/errors.go
- internal/sqlib/sqerrors/errors_test.go
- internal/sqlib/sqtime/backoff.go
Critical execution errors happening in the request hot path are now logged according to exponential backoff counters of their occurrences. This avoids slowing down request handlers but also spamming the internal agent queue. Such error will now go through the agent error logging facility every time the backoff counter is a power of two (1, 2, 4, 8, etc.). This is disabled when in debug log level.
> Hot-path error management

- sdk/middleware/sqecho/echo_test.go
- sdk/middleware/sqgin/gin.go
- sdk/middleware/sqgin/gin_test.go
- sdk/middleware/sqhttp/http_test.go
Fix the response's content-length monitoring with the default response (ie. the handler does nothing).
> sdk/middleware/sqgin: response's content length monitoring

- internal/actor/action.go
- internal/actor/http.go
- internal/backend/api/signal/signal.go
- internal/plog/plog.go
- internal/plog/plog_test.go
- internal/protection/context/_testlib/mockup.go
- internal/protection/http/_testlib/mockups/mockups.go
- internal/protection/http/http.go
- internal/rule/callback/security-responses.go
- internal/rule/callback/security-responses_test.go
- internal/rule/callback/shellshock_unit_test.go
- sdk/middleware/_testlib/mockups/http.go
Enable the correct event display on the dashboard by fixing the track event name with
the one the backend actually expects.
Also, restoring the security response tests highlighted some inconsistent blocking behavior
between user/ip blocking/redirecting that are now fixed.
> Security Responses: fix the name of security response action events

- internal/protection/context/_testlib/mockup.go
- sdk/sdk.go
- sdk/sdk_test.go
Moving to an interface-only public API has the benefit of hiding the
type-implementation details that may change over time in the future. The
returned SDK values are now interface values and no longer pointer values. This
may break integrations having explicit types. We recommend to instead use
type-inference when possible.
From now, this change will allow us to transparently change the underlying
values returned by SDK calls. For example, as of today, the underlying SDK
values are small event collection wrappers that shouldn't be returned by
reference in order to avoid useless allocations, for the benefit of the overall
application performance. If the underlying object size increase in the future,
we will be able to return allocated structures instead without breaking existing
SDK …
> SDK: interface-only public API

- internal/protection/http/bindingaccessor.go
- internal/protection/http/bindingaccessors_test.go
- internal/protection/http/http.go
- internal/protection/http/types/types.go
- internal/rule/callback/write-blocking-html-page.go
- sdk/middleware/sqecho/echo.go
- sdk/middleware/sqecho/echo_test.go
- sdk/middleware/sqecho/v4/echo.go
- sdk/middleware/sqecho/v4/echo_test.go
- sdk/middleware/sqgin/gin.go
- sdk/middleware/sqgin/gin_test.go
- sdk/middleware/sqhttp/http.go
- sdk/middleware/sqhttp/http_test.go
- sdk/middleware/sqhttp/response-writer-adapter.go
- sdk/middleware/sqhttp/response-writer-adapter_test.go
- sdk/middleware/sqhttp/response.go
- sdk/sqreen-instrumentation-tool/testdata/hello-gls/main.go
Make the HTTP response writer wrapper transparent by implementing the same
*known* interfaces as the underlying HTTP response writer. The
list of interfaces is currently every optional `net/http` interfaces, and some
from `io` when relevant:
- `http.Flusher`: to allow flushing any buffered to the client. This enables
support for streaming handlers.
- `http.Hijacker`: to allow handlers to takeover the HTTP connection. This
should enable the support for websocket servers, which are not officially
supported by Sqreen, but is now experimentally allowed.
- `http.Pusher`: for HTTP2 server push.
- `http.CloseNotifier`: the deprecated closed connection notifier.
- `io.ReaderFrom`: for optimized copies (eg. `io.Copy(file, w)`)
- `io.WriteString`: for optimized string write (which avoids a …
> sdk/middleware/sqhttp: transparent http response writer wrapper

- sdk/sdk.go
Add `sdk.FromRequest()` helper function to retrieve Sqreen's SDK handle from a request.
It is a shortcut to `sdk.FromContext(r.Context())`.
> sdk: add FromRequest() helper
